### ISSUE TITLE
Not working for *.vue file

### ISSUE THREAD

**Issue by tsball** [GlebkaF/eslint-plugin-strict-vue#7]
I have install it, and config as the readme.
Then I run "eslint src/App.vue".
It is not working, it will not check the methods in <script/>

I have installed the jsdoc, and the command "eslint src/helpers/my.js" works.

**Comment by GlebkaF** [comment]
Hey!

Could you provide your App.vue file, so I can reproduce the case.
I'm using the plugin with vue files and it's just fine
